allowedPictureExt = ['png', 'jpg', 'jpeg']
itemImagePath = 'Database/Pictures/Item/'
userImagePath = 'Database/Pictures/User/'
allowedPictureExt = ['png', 'jpg', 'jpeg']
title = 'VT Shop'
perPageItem = 5
perPageUser = 5
restrictedUser = ("Customer")
specialUser = ("Owner", "Admin")