allowedPictureExt = ['png', 'jpg', 'jpeg']
itemImagePath = 'Database/Pictures/Item/'
userImagePath = 'Database/Pictures/User/'
title = 'VT Shop'
perPageItem = 5
perPageUser = 5
restrictedUser = ("Customer")
specialUser = ("Owner", "Admin")
itemOutputSize = 512, 512
userOutputSize = 128, 128